### ISSUE TITLE
Alias RGB888 to the RGB module

### ISSUE THREAD

**Issue by supersimple** [supersimple/chameleon#14]
In some libraries, 8 bit RGB is referred to as RGB888. In order to avoid confusion, alias the current RGB module to also work by using that names.

**Comment by fhunleth** [comment]
I feel like I messed this one up when I suggested an RGBf format. I actually haven't seen RGB8 in my work. Here are the RGB formats that I commonly work with:

* RGB888 - separate red, green, and blue 8-bits each
* ARGB888 - RGB888 with 8-bit alpha. Alpha can be premultiplied or not.
* RGBf - separate red, green, and blue components that are floats in the range 0.0 to 1.0. Normally the number of bits in the float are specified, but I don't think that makes sense here.
* RGB24, ARGB32, BGR24, etc. - A 32-bit integers with 8-bits for red, green, blue and optionally alpha. 

Related to this discussion, there's a thing called Gray8 that's 8-bit grayscale.

Just to be clear, I'm not advocating support for all of these. The integer representations make more sense if you're manipulating image bitmaps and I don't think that's a use case for Chameleon.
