### ISSUE TITLE
Remove explicit conversion functions that convert through RGB

### ISSUE THREAD

**Issue by fhunleth** [supersimple/chameleon#7]
This now happens automatically by default, so the functions aren't needed. 

For example, this [module](https://github.com/supersimple/chameleon/blob/v2/lib/chameleon/hsl.ex#L13-L23) can be deleted as well as this [function](https://github.com/supersimple/chameleon/blob/v2/lib/chameleon/hsl.ex#L90-L102) without loss of functionality.

Deleting this does delete a doctest, though, so it would be good to move that to a unit test when making this update.

**Comment by supersimple** [comment]
Fixed with https://github.com/supersimple/chameleon/pull/9
